package com.melbourneit.usermanagement.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-04-05T17:29:23.733+08:00
 * Generated source version: 2.7.4
 * 
 */
@WebServiceClient(name = "MyAccountService", 
                  wsdlLocation = "file:/C:/Development/references/fuse-source/MyAccountService.wsdl",
                  targetNamespace = "http://service.usermanagement.melbourneit.com") 
public class MyAccountService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.usermanagement.melbourneit.com", "MyAccountService");
    public final static QName MyAccountServiceHttpPort = new QName("http://service.usermanagement.melbourneit.com", "MyAccountServiceHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Development/references/fuse-source/MyAccountService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MyAccountService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Development/references/fuse-source/MyAccountService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MyAccountService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MyAccountService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyAccountService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    

    /**
     *
     * @return
     *     returns MyAccountServicePortType
     */
    @WebEndpoint(name = "MyAccountServiceHttpPort")
    public MyAccountServicePortType getMyAccountServiceHttpPort() {
        return super.getPort(MyAccountServiceHttpPort, MyAccountServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyAccountServicePortType
     */
    @WebEndpoint(name = "MyAccountServiceHttpPort")
    public MyAccountServicePortType getMyAccountServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(MyAccountServiceHttpPort, MyAccountServicePortType.class, features);
    }

}
