package com.melbourneit.usermanagement.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-04-05T17:29:23.697+08:00
 * Generated source version: 2.7.4
 * 
 */
@WebService(targetNamespace = "http://service.usermanagement.melbourneit.com", name = "MyAccountServicePortType")
@XmlSeeAlso({ObjectFactory.class, com.melbourneit.usermanagement.client.ObjectFactory.class})
public interface MyAccountServicePortType {

    @WebResult(name = "out", targetNamespace = "http://service.usermanagement.melbourneit.com")
    @RequestWrapper(localName = "getMyAccount", targetNamespace = "http://service.usermanagement.melbourneit.com", className = "com.melbourneit.usermanagement.service.GetMyAccount")
    @WebMethod
    @ResponseWrapper(localName = "getMyAccountResponse", targetNamespace = "http://service.usermanagement.melbourneit.com", className = "com.melbourneit.usermanagement.service.GetMyAccountResponse")
    public com.melbourneit.usermanagement.client.MyAccountVO getMyAccount(
        @WebParam(name = "in0", targetNamespace = "http://service.usermanagement.melbourneit.com")
        java.lang.String in0
    );
}
